/**
 * XLIFF, TMX, and TBX generation/parsing for professional translation tool interoperability.
 */

// ============================================================
// XLIFF 2.1 Generation (with 1.2 backward compat structure)
// ============================================================

interface XliffSegment {
  id: string
  source: string
  target: string
  state: 'initial' | 'translated' | 'reviewed' | 'final'
  note?: string
  score?: number
}

export function generateXliff(opts: {
  jobRef: string
  sourceLang: string
  targetLang: string
  segments: XliffSegment[]
  contentType?: string
}): string {
  const units = opts.segments.map(seg => `    <unit id="${seg.id}">
      <segment state="${seg.state}">
        <source>${escapeXml(seg.source)}</source>
        <target>${escapeXml(seg.target)}</target>
      </segment>${seg.note ? `
      <notes>
        <note category="vera-review">${escapeXml(seg.note)}</note>
      </notes>` : ''}${seg.score !== undefined ? `
      <mda:metadata>
        <mda:metaGroup category="vera-scores">
          <mda:meta type="hter-score">${seg.score}</mda:meta>
        </mda:metaGroup>
      </mda:metadata>` : ''}
    </unit>`).join('\n')

  return `<?xml version="1.0" encoding="UTF-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:2.0"
       xmlns:mda="urn:oasis:names:tc:xliff:metadata:2.0"
       version="2.0"
       srcLang="${opts.sourceLang}"
       trgLang="${opts.targetLang}">
  <file id="${opts.jobRef}" original="${opts.jobRef}">
    <notes>
      <note category="vera-meta">Generated by Vera — Human-verified AI translation governance</note>
      <note category="content-type">${opts.contentType ?? 'general'}</note>
      <note category="generated-at">${new Date().toISOString()}</note>
    </notes>
${units}
  </file>
</xliff>`
}

// ============================================================
// XLIFF Parsing (extract segments from uploaded XLIFF)
// ============================================================

export function parseXliff(xml: string): { sourceLang: string; targetLang: string; segments: { source: string; target: string }[] } {
  // Extract languages
  const srcMatch = xml.match(/srcLang="([^"]+)"/) || xml.match(/source-language="([^"]+)"/)
  const trgMatch = xml.match(/trgLang="([^"]+)"/) || xml.match(/target-language="([^"]+)"/)
  const sourceLang = srcMatch?.[1] ?? 'EN'
  const targetLang = trgMatch?.[1] ?? 'DE'

  // Extract translation units (handles both XLIFF 1.2 and 2.0)
  const segments: { source: string; target: string }[] = []

  // XLIFF 2.0 pattern: <segment><source>...</source><target>...</target></segment>
  const segRegex = /<source[^>]*>([\s\S]*?)<\/source>\s*<target[^>]*>([\s\S]*?)<\/target>/g
  let match
  while ((match = segRegex.exec(xml)) !== null) {
    const source = unescapeXml(match[1].trim())
    const target = unescapeXml(match[2].trim())
    if (source) segments.push({ source, target: target || source })
  }

  // XLIFF 1.2 pattern: <trans-unit><source>...</source><target>...</target></trans-unit>
  if (segments.length === 0) {
    const tuRegex = /<trans-unit[^>]*>[\s\S]*?<source[^>]*>([\s\S]*?)<\/source>[\s\S]*?<target[^>]*>([\s\S]*?)<\/target>[\s\S]*?<\/trans-unit>/g
    while ((match = tuRegex.exec(xml)) !== null) {
      const source = unescapeXml(match[1].trim())
      const target = unescapeXml(match[2].trim())
      if (source) segments.push({ source, target: target || source })
    }
  }

  return { sourceLang, targetLang, segments }
}

// ============================================================
// TMX Generation (Translation Memory eXchange)
// ============================================================

interface TmxUnit {
  source: string
  target: string
  sourceLang: string
  targetLang: string
  date?: string
  project?: string
  contentType?: string
}

export function generateTmx(opts: {
  orgName: string
  units: TmxUnit[]
}): string {
  const tus = opts.units.map((u, i) => `    <tu tuid="${i + 1}" creationdate="${u.date ? new Date(u.date).toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z' : new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z'}">
      <prop type="x-vera-project">${escapeXml(u.project ?? '')}</prop>
      <prop type="x-vera-content-type">${escapeXml(u.contentType ?? '')}</prop>
      <tuv xml:lang="${u.sourceLang}">
        <seg>${escapeXml(u.source)}</seg>
      </tuv>
      <tuv xml:lang="${u.targetLang}">
        <seg>${escapeXml(u.target)}</seg>
      </tuv>
    </tu>`).join('\n')

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tmx SYSTEM "tmx14.dtd">
<tmx version="1.4">
  <header creationtool="Vera" creationtoolversion="1.0"
          datatype="PlainText" segtype="sentence"
          adminlang="en" srclang="*all*"
          o-tmf="Vera Translation Memory">
    <prop type="x-vera-org">${escapeXml(opts.orgName)}</prop>
    <prop type="x-vera-exported">${new Date().toISOString()}</prop>
  </header>
  <body>
${tus}
  </body>
</tmx>`
}

// ============================================================
// TBX Generation (TermBase eXchange)
// ============================================================

interface TbxEntry {
  sourceTerm: string
  targetLang: string
  translation: string
  doNotTranslate?: boolean
  notes?: string
}

export function generateTbx(opts: {
  orgName: string
  entries: TbxEntry[]
}): string {
  const conceptEntries = opts.entries.map((e, i) => `      <conceptEntry id="c${i + 1}">
        <langSec xml:lang="en">
          <termSec>
            <term>${escapeXml(e.sourceTerm)}</term>${e.doNotTranslate ? `
            <termNote type="termType">do-not-translate</termNote>` : ''}
          </termSec>
        </langSec>
        <langSec xml:lang="${e.targetLang}">
          <termSec>
            <term>${escapeXml(e.translation)}</term>${e.notes ? `
            <note>${escapeXml(e.notes)}</note>` : ''}
          </termSec>
        </langSec>
      </conceptEntry>`).join('\n')

  return `<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://raw.githubusercontent.com/LTAC-Global/TBX-Basic_dialect/master/DCA/TBXcoreStructV03_TBX-Basic_integrated.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<tbx style="dca" type="TBX-Basic" xml:lang="en"
     xmlns="urn:iso:std:iso:30042:ed-2">
  <tbxHeader>
    <fileDesc>
      <titleStmt>
        <title>${escapeXml(opts.orgName)} — Vera Terminology</title>
      </titleStmt>
      <sourceDesc>
        <p>Exported from Vera on ${new Date().toISOString()}</p>
      </sourceDesc>
    </fileDesc>
  </tbxHeader>
  <text>
    <body>
${conceptEntries}
    </body>
  </text>
</tbx>`
}

// ============================================================
// TBX Parsing (import terminology)
// ============================================================

export function parseTbx(xml: string): TbxEntry[] {
  const entries: TbxEntry[] = []
  const conceptRegex = /<conceptEntry[^>]*>([\s\S]*?)<\/conceptEntry>/g
  let match

  while ((match = conceptRegex.exec(xml)) !== null) {
    const block = match[1]
    const langSecs = block.match(/<langSec[^>]*>([\s\S]*?)<\/langSec>/g) ?? []

    let sourceTerm = ''
    let targetLang = ''
    let translation = ''
    let notes = ''

    for (const ls of langSecs) {
      const langMatch = ls.match(/xml:lang="([^"]+)"/)
      const termMatch = ls.match(/<term>([\s\S]*?)<\/term>/)
      const noteMatch = ls.match(/<note>([\s\S]*?)<\/note>/)
      const lang = langMatch?.[1] ?? ''
      const term = termMatch ? unescapeXml(termMatch[1].trim()) : ''

      if (lang === 'en' || lang.startsWith('en-')) {
        sourceTerm = term
      } else {
        targetLang = lang
        translation = term
        if (noteMatch) notes = unescapeXml(noteMatch[1].trim())
      }
    }

    if (sourceTerm && translation) {
      const dnt = block.includes('do-not-translate')
      entries.push({ sourceTerm, targetLang: targetLang.toUpperCase(), translation, doNotTranslate: dnt, notes: notes || undefined })
    }
  }

  return entries
}

// ============================================================
// Helpers
// ============================================================

function escapeXml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;')
}

function unescapeXml(s: string): string {
  return s.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&apos;/g, "'")
}

/**
 * Trigger file download in the browser.
 */
export function downloadFile(content: string, filename: string, mimeType = 'application/xml') {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
