/**
 * Seeds help articles for all roles.
 * Run: npx tsx scripts/seed-help.ts
 */
import 'dotenv/config'
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(process.env.VITE_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { autoRefreshToken: false, persistSession: false } })

const articles = [
  // CLIENT ARTICLES
  { slug: 'welcome-client', title: 'Welcome to Vera', body: `What this does: Vera provides human-verified governance for your AI translations.\n\nHow to use it:\n1. Submit AI-translated content through the platform\n2. Expert linguists review and score it against six quality criteria\n3. Receive verified content with full audit trail and AI Health Score\n\nVera doesn't translate — it reviews, scores, and certifies your AI translations as safe to publish.`, category: 'getting_started', audience: ['client'], order_index: 1 },
  { slug: 'submit-job', title: 'How to submit a job', body: `What this does: Upload AI-translated content for expert review.\n\nHow to use it:\n1. Go to Submit Work in the top nav\n2. Upload your file (.docx, .txt, .csv, .pdf, .xliff)\n3. Select source and target language\n4. Choose content type and AI tool used\n5. Select Standard (24h) or Expedited (6h) turnaround\n6. Add any notes for the reviewer\n7. Click Submit\n\nThings to watch out for:\n- Word count is extracted automatically for .docx and .txt files\n- Expedited jobs cost 50% more but are prioritised`, category: 'submitting_work', audience: ['client'], order_index: 1 },
  { slug: 'ai-health-score', title: 'Understanding your AI Health Score', body: `What this does: Your AI Health Score (0-100) measures how well your AI translation tools perform.\n\nHow it works:\n- 100 = perfect (no editing needed)\n- 0 = needs complete rewrite\n- Based on hTER (human-targeted edit rate) across all your reviewed jobs\n- Updated daily from the last 90 days of delivered work\n\nThe score breaks down by:\n- Language pair (EN→DE may perform differently to EN→FR)\n- Content type (marketing vs compliance)\n- AI tool used (ChatGPT vs DeepL vs Claude)\n\nUse this to make data-driven decisions about which AI tools to use for which content.`, category: 'ai_features', audience: ['client'], order_index: 1 },
  { slug: 'hter-explained', title: 'What is hTER and why it matters', body: `What this does: hTER (human-targeted edit rate) measures how much a human reviewer had to change the AI output.\n\nHow to read it:\n- 0.00 = no changes needed (perfect AI output)\n- 0.15 = minor edits (strong performance)\n- 0.25 = moderate editing (typical)\n- 0.35+ = significant rework needed\n- Industry average: 0.31\n\nVera calculates hTER from six criteria scores: accuracy, terminology, tone & register, brand voice, cultural fit, and risk assessment.`, category: 'scoring', audience: ['client', 'reviewer'], order_index: 1 },
  { slug: 'audit-trail', title: 'Reading your audit trail', body: `What this does: Every action on your jobs is recorded in a permanent audit trail.\n\nHow to use it:\n1. Go to AI Health & Audit\n2. Scroll to the Audit Trail section\n3. Each row shows: date, job reference, content type, language pair, reviewer, hTER score\n\nThe Export PDF button generates a branded report suitable for procurement, board, or regulatory review. This is Vera's governance story — every decision documented and defensible.`, category: 'scoring', audience: ['client'], order_index: 2 },
  { slug: 'subscription', title: 'Managing your subscription', body: `What this does: View your tier, track word usage, and manage billing.\n\nHow to use it:\n1. Go to Subscription in the nav\n2. See your current tier, monthly price, and word allowance\n3. Track usage with the progress bar\n4. Compare other available tiers\n\nIf you approach your allowance, you'll see options to pay overflow, upgrade for one month, or upgrade permanently.`, category: 'account', audience: ['client'], order_index: 1 },
  { slug: 'glossary', title: 'Adding terminology to your glossary', body: `What this does: Your glossary ensures consistent terminology across all reviews.\n\nHow to use it:\n1. Go to Glossary in the nav\n2. Add terms: source word, target language, preferred translation\n3. Mark "Do not translate" for brand names\n4. Add brand voice notes: guidelines, tone descriptors, forbidden phrases\n\nReviewers see your glossary when scoring. Vera's AI pre-flight check flags violations automatically. The more terms you add, the more consistent your translations become.`, category: 'ai_features', audience: ['client'], order_index: 2 },
  { slug: 'troubleshooting-login', title: 'Troubleshooting login issues', body: `Common issues:\n\n1. Magic link expired: Links expire after 1 hour. Request a new one.\n2. Email not received: Check spam/junk. If using a corporate email, check with IT.\n3. Password not working: Use the magic link option, or contact emma@ecls-translations.com to reset.\n4. Wrong portal: If you land on the wrong portal, you'll be redirected automatically based on your role.`, category: 'troubleshooting', audience: ['client', 'reviewer', 'salesperson', 'admin'], order_index: 1 },

  // REVIEWER ARTICLES
  { slug: 'welcome-reviewer', title: 'Welcome to Vera — how you fit in', body: `What this does: As a Vera reviewer, you're the human expert in the loop.\n\nYour role:\n1. Receive assigned jobs in your queue\n2. Review AI-translated content against six quality criteria\n3. Score each criterion 1-10 and annotate segments\n4. Submit for Emma's sign-off\n\nYou see: the source text, the AI translation, pre-flight check data, the client's glossary, and brand voice notes. Everything you need to deliver an expert review.`, category: 'getting_started', audience: ['reviewer'], order_index: 1 },
  { slug: 'scoring-criteria', title: 'The six scoring criteria explained', body: `Each job is scored 1-10 on:\n\n1. Accuracy — Does the translation preserve the source meaning?\n2. Terminology — Are technical/specialist terms correctly used?\n3. Tone & register — Is the formality and voice appropriate?\n4. Brand voice — Does it align with client style and brand guidelines?\n5. Cultural fit — Is it natural and appropriate for the target locale?\n6. Risk — Are there safety, legal or reputational concerns? (10 = no risk)\n\nThese six scores combine into a single hTER score per job. Be honest and consistent — your scores drive the client's AI Health Score and inform their decisions about AI tool selection.`, category: 'scoring', audience: ['reviewer'], order_index: 1 },
  { slug: 'segment-annotation', title: 'Segment-level annotation', body: `What this does: Edit individual segments of the AI translation inline.\n\nHow to use it:\n1. Open a job from your queue\n2. Each segment shows source (left) and AI translation (right)\n3. Click into the AI translation to edit\n4. Set severity: Fine / Minor / Major / Critical\n5. Add optional comments per segment\n6. Changes auto-save on blur\n\nThe sticky header shows: total segments, edited count, severity counts. Pre-flight flags appear inline on segments with potential issues.`, category: 'scoring', audience: ['reviewer'], order_index: 2 },
  { slug: 'reviewer-invoice', title: 'Submitting your invoice', body: `What this does: Submit monthly invoices for your completed work.\n\nHow to use it:\n1. Go to Invoices in the nav\n2. Click Create Invoice\n3. System auto-pulls delivered jobs for the period\n4. Review line items and totals\n5. Toggle VAT if applicable\n6. Add optional note to Emma\n7. Submit\n\nEmma reviews and approves. Once approved, payment is scheduled for the 28th.`, category: 'invoicing', audience: ['reviewer'], order_index: 1 },
  { slug: 'reviewer-earnings', title: 'Understanding your earnings', body: `What this does: Track what you've earned and what's coming.\n\nHow to use it:\n1. Go to Earnings in the nav\n2. See this month, last month, YTD totals\n3. Monthly statements show words reviewed and amounts\n4. Current month = Pending (paid on 28th)\n5. Past months = Paid\n\nYour rate is set per word. Total = words reviewed × rate.`, category: 'invoicing', audience: ['reviewer'], order_index: 2 },
  { slug: 'connect-bank', title: 'Connecting your bank account', body: `What this does: Set up Stripe Connect to receive payouts.\n\nHow to use it:\n1. Go to Settings in the nav\n2. Click Connect bank account\n3. Complete Stripe's hosted onboarding (KYC, bank details, tax)\n4. Once verified, payouts are automatic on the 28th\n\nYou can complete reviews before connecting — payouts are held until onboarding is done.`, category: 'account', audience: ['reviewer', 'salesperson'], order_index: 1 },

  // SALESPERSON ARTICLES
  { slug: 'welcome-sales', title: 'Welcome to Vera Sales', body: `What this does: Track your leads, manage your pipeline, and earn commissions.\n\nYour tools:\n- Leads: track prospects from first contact to close\n- My Clients: see introduced organisations and their MRR\n- Earnings: commission payout history\n- Settings: bank connection for payouts`, category: 'getting_started', audience: ['salesperson'], order_index: 1 },
  { slug: 'managing-leads', title: 'Adding and managing leads', body: `What this does: Track prospects through the sales pipeline.\n\nHow to use it:\n1. Go to Leads in the nav\n2. Click Add Lead — fill in contact, company, estimated MRR\n3. View as Kanban (columns by stage) or List\n4. Click any lead for full detail\n5. Change stage, add notes, log activities\n6. Convert qualified leads to quotes\n\nStages: New → Contacted → Qualified → Demo booked → Proposal sent → Negotiating → Won/Lost`, category: 'sales', audience: ['salesperson'], order_index: 1 },
  { slug: 'commission-terms', title: 'Understanding commission terms', body: `What this does: Your commission is based on the MRR of clients you introduce.\n\nTwo types:\n- Finder's fee: one-off percentage of first year value\n- Recurring: monthly percentage of the client's MRR\n\nYour default terms are set by Emma and shown on your profile. Individual agreements may have custom terms. Commissions are calculated monthly and paid on the 28th.`, category: 'invoicing', audience: ['salesperson'], order_index: 1 },

  // ADMIN ARTICLES
  { slug: 'admin-overview', title: 'Vera admin overview', body: `What this does: Emma's operational hub for running the entire Vera business.\n\nKey areas:\n- Dashboard: today's priorities, MRR, capacity\n- Operations: jobs, audit log, scheduled tasks\n- People: clients, reviewers, salespeople\n- Pipeline: leads, quotes, invoices\n- AI Insights: tool performance, recommendations\n- Settings: tier pricing, integrations`, category: 'admin', audience: ['admin'], order_index: 1 },
  { slug: 'allocating-jobs', title: 'Allocating jobs to reviewers', body: `What this does: Assign incoming jobs to the right reviewer.\n\nHow to use it:\n1. Go to Jobs\n2. Click an unallocated job\n3. The reviewer list shows best matches first (language pair match, then lowest active jobs)\n4. Select reviewer and confirm\n5. Reviewer receives email notification\n\nTip: Language pair matching is the most important factor. A native DE speaker should review EN→DE content.`, category: 'admin', audience: ['admin'], order_index: 1 },
  { slug: 'signing-off', title: 'Signing off and returning work', body: `What this does: Review completed work and either deliver or return for revision.\n\nSign off:\n1. Open an "awaiting signoff" job\n2. Review the six-criteria scores and hTER\n3. Read reviewer notes\n4. Click "Sign off & deliver"\n5. Client receives notification\n\nReturn:\n1. Click "Return to reviewer"\n2. Write feedback (min 20 chars)\n3. Reviewer sees your notes and can revise`, category: 'admin', audience: ['admin'], order_index: 2 },
  { slug: 'tier-pricing', title: 'Managing tier pricing', body: `What this does: Edit subscription tiers and pricing.\n\nHow to use it:\n1. Go to Settings (gear icon)\n2. Edit tier names, prices, word allowances, overflow rates\n3. Set PAYG rate, expedited surcharge, Health Check fee\n4. Click Save\n\nChanges apply to new clients immediately. Existing clients keep original terms until renewal.`, category: 'admin', audience: ['admin'], order_index: 3 },
  { slug: 'inviting-users', title: 'Inviting clients, reviewers, salespeople', body: `What this does: Onboard new users to Vera.\n\nClients:\n1. Go to Clients → Add client\n2. Fill in name, email, organisation, tier\n3. System creates org, subscription, user, sends welcome email\n\nReviewers:\n1. Go to Reviewers → Add reviewer\n2. Add language pairs, specialism, rate\n3. Welcome email sent\n\nSalesspeople:\n1. Go to Sales → Add salesperson\n2. Set default commission terms\n3. Welcome email sent\n\nAll users get the password VeraDemo2026! initially.`, category: 'admin', audience: ['admin'], order_index: 4 },
  { slug: 'demo-live-modes', title: 'Resetting and reinstalling demo data', body: `What this does: Manage demo and live data independently.\n\nDemo mode: seeded walkthrough data for prospects.\nLive mode: real client data for production.\n\nTo reset:\n1. Go to /admin/system-reset\n2. "Reinstall demo data" — wipes and re-seeds demo (type REINSTALL DEMO)\n3. "Wipe demo data" — empties demo mode (type WIPE DEMO)\n4. "Wipe live data" — clears production data (type RESET LIVE)\n\nDemo and live data are separated by the is_demo flag.`, category: 'admin', audience: ['admin'], order_index: 5 },
]

async function seed() {
  console.log('Seeding help articles...\n')
  await supabase.from('help_articles').delete().neq('id', '00000000-0000-0000-0000-000000000000')

  const { error } = await supabase.from('help_articles').insert(articles)
  if (error) throw error
  console.log(`${articles.length} articles seeded.`)
}

seed().catch(console.error)
